"""Import the reviewed June 2026 TOP500 HTML snapshot. No node counts inferred from cores."""
import html, json, re
from pathlib import Path

def clean(s):
    return ' '.join(html.unescape(re.sub('<[^>]+>', ' ', s)).split())

rows=[]
for tr in re.findall(r'<tr[^>]*>(.*?)</tr>',Path('.sites-runtime/top500-full.html').read_text(encoding='utf-8'),re.S):
    cells=re.findall(r'<td[^>]*>(.*?)</td>',tr,re.S)
    if not cells or not clean(cells[0]).isdigit() or int(clean(cells[0]))>50: continue
    rank=int(clean(cells[0])); anchors=re.findall(r'<a href="([^"]+)"[^>]*>(.*?)</a>',cells[1],re.S)
    desc=clean(anchors[0][1]); name_match=re.search(r'<b>(.*?)</b>',anchors[0][1],re.S)
    name=clean(name_match[1]) if name_match else 'Shakti Cloud · XE9680'
    hardware=desc.split(' - ',1)[-1] if name_match else desc
    fields=[s.strip() for s in hardware.split(',') if s.strip()]
    cpu=fields[1]; gpu=next((f for f in fields[2:] if re.search(r'NVIDIA|Nvidia|AMD Instinct|Intel Data Center GPU',f) and not re.search(r'Infini|Infiniband|HDR|NDR',f)),None)
    network=next((f for f in fields[2:] if re.search(r'Slingshot|[Ii]nfini|LingQi|Tofu|Sunway|RoCE|BCM|BXI|Ethernet',f)),'Not verified')
    country=clean(cells[1].split('</a>')[-1])
    ident=re.sub(r'[^a-z0-9]+','-',name.lower()).strip('-')
    if rank==32: ident='shakti-cloud'
    if rank==39: ident='nipa-kakao'; name='NIPA (Kakao)'
    if rank==46: ident='core42-superpod'; name='Core42 SuperPOD'
    if rank==23: ident='eos'; name='Eos'
    no_gpu=rank==27
    p=dict(name=fields[0]+' · public profile',count=None,cpu=cpu,cpus=None,gpu=gpu,gpus=0 if no_gpu else None,ram='Not verified',vram='Not applicable' if no_gpu else 'Not verified',link='Not applicable' if no_gpu else 'Not verified',hostLink='Not verified',disk='Not verified')
    rows.append(dict(id=ident,name=name,site=clean(anchors[1][1]),country=country,rank=rank,rmax=float(clean(cells[3]).replace(',','')),network=network,topology='Not verified',parts=[p],sources=[dict(title='TOP500 · June 2026 ranking',url='https://top500.org/lists/top500/list/2026/06/'),dict(title='TOP500 · system record',url='https://top500.org'+anchors[0][0])],notes='Partial public profile: processor and fabric follow the TOP500 submission. Node count, socket count, memory and on-node wiring are not assumed from the server model or benchmark core count. This entry describes the ranked system or partition, not every resource operated at this site.',profileScope='Ranked system / partition',checked='14 September 2026',hardwareDescription=hardware))
assert [c['rank'] for c in rows]==list(range(1,51))
# Core count, theoretical peak, measured power, manufacturer and operating system
# are published for the ranked table too, but are not part of each system record's
# detail page. They are transcribed into dist/ranked-extras.js instead of being
# written here, so re-importing this snapshot does not silently drop them again.
Path('dist/top50.js').write_text('// Reviewed ranking snapshot. Generated by scripts/import-top50.py.\nexport const top50 = '+json.dumps(rows,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print('Imported 50 ranked records; existing detailed profiles are merged by rank/name.')
print('NOTE: dist/ranked-extras.js holds ranked cores, Rpeak, power, OS and manufacturer;')
print('      keep it in step with the snapshot when ranks change.')
